service: banktool

provider:
  name: aws
  runtime: python3.6
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    BASE_PATH: ${env:BASE_PATH}
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - dynamodb:BatchWriteItem
    Resource:
      - "Fn::GetAtt": [ PasswordsTable, Arn ]


package:
  include:
    - bcse/**
    - belarusbank/**
    - mtbank/**
    - passwords/**
    - constants.py
    - serverless_utils.py
    - keys.json
  exclude:
    - ./**

custom:
  pythonRequirements:
    fileName: requirements/serverless.txt
    pythonBin: python
    useDownloadCache: true
    cacheLocation: .serverless/.cache

functions:
  bcse:
    handler: bcse.utils.serverless_get_data
    events:
      - http:
          path: bcse
          method: get
      - schedule: cron(*/15 7-12 ? * MON-FRI *)

  mtbank:
    handler: mtbank.serverless.overview
    events:
      - http:
          path: mtb
          method: get

  belarusbank:
    handler: belarusbank.serverless.overview
    events:
      - http:
          path: bb
          method: get

  auth-get:
    handler: passwords.serverless.get_password
    events:
      - http:
          path: auth
          method: get

  auth-post:
    handler: passwords.serverless.post_password
    events:
      - http:
          path: auth
          method: post

  clear-db:
    handler: passwords.serverless.clear_sessions
    events:
      - schedule: cron(0 */3 * * ? *)


resources:
  Resources:
    PasswordsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: passwords-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1




plugins:
  - serverless-python-requirements
