version: 2
jobs:
  build:
    docker:
     - image: circleci/python:3.6.6-stretch-node-browsers
    steps:
     - checkout

     - run:
         name: Create requirements.txt
         command: |
           python3.6 -m venv env
           . env/bin/activate
           pip install pip-tools
           pip-compile requirements/dev.in
           pip-compile requirements/serverless.in

     - restore_cache:
         name: Restore venv.
         key: python3.6.6-v1-{{ checksum "requirements/dev.txt" }}

     - run:
         name: Install python dependencies.
         command: |
           python3.6 -m venv env
           . env/bin/activate
           pip install -r requirements/dev.txt

     - save_cache:
         name: Save venv.
         key: python3.6.6-v1-{{ checksum "requirements/dev.txt" }}
         paths:
          - env

     - run:
         name: pytest
         command: |
           . env/bin/activate
           python -m pytest

     - run:
         name: Install and prepare serverless.
         command: |
           sudo npm i -g serverless
           npm install
           mkdir .serverless

     - restore_cache:
         name: Restore serverless cache.
         key: sls-python3.6.6-v1-{{ checksum "requirements/serverless.txt" }}

     - run:
         name: Prepare a package.
         command: |
           . env/bin/activate
           if [ "${CIRCLE_BRANCH}" == "master" ]; then
            export BASE_PATH="/"
           fi

           serverless package -s "$CIRCLE_BRANCH"

     - save_cache:
         name: Save serverless cache.
         key: sls-python3.6.6-v1-{{ checksum "requirements/serverless.txt" }}
         paths:
          - .serverless/.cache

     - run:
         name: Deploy to aws.
         command: serverless deploy -s "$CIRCLE_BRANCH"
